### ISSUE TITLE
Solace 

### ISSUE THREAD

**Issue by CrafterDungin** [mygameplatform/public#4]
## **Game** 

Solace Crafting

## **Links for the download SteamCMD**

https://steamdb.info/app/1086950/config/
## **Installation guide**

https://solace-crafting.fandom.com/wiki/Dedicated_Server_Setup_Guide

**Comment by killertobyd** [comment]
hi @CrafterDungin ,
i have been looking at the game and need to see if I can find another server guide.

**Comment by CrafterDungin** [comment]
Would be cool if that works out with the game

**Comment by killertobyd** [comment]
hi @CrafterDungin 
The game is finished and will be available in the catalog on mygameplatform.com in the near future.
