### ISSUE TITLE
Sons of the Forest

### ISSUE THREAD

**Issue by CrafterDungin** [mygameplatform/public#5]
## **Game** 
 Sons of the Forest

## **References**

Have not steamcmd and guide found

**Comment by fo0** [comment]
https://www.videogamer.com/tech/sons-of-the-forest-dedicated-server/

**Comment by fo0** [comment]
@CrafterDungin could you please ask a question how we can help you ? :) Just opening a case with a title does not lead to a question

**Comment by CrafterDungin** [comment]
I wish the game in your catalog.  I wait then that it is in the catalog

**Comment by fo0** [comment]
Alright. I don't know if and when the game is planned for a release on our platform. @killertobyd will get in contact in next days and will clearify that.  But as far as I know its at the pipe 👍

**Comment by killertobyd** [comment]
Sorry, there are no servers for the game at the moment. As soon as this is possible, I will work on this issue

**Comment by killertobyd** [comment]
done
